### ISSUE TITLE
Add GPS data to JPEGs

### ISSUE THREAD

**Issue by hatobi** [hatobi/bereal-gdpr-photo-toolkit#1]
It's possible to add a location to BeReal-photos but as I never allowed the app to access my location, the GDPR export also does not contain location data. I'd guess that if you enabled this, the JSON should also come with this data which could then be added to the JPEGs. I'd be happy to implement it if someone could send me the data structure.

**Comment by U14-dev** [comment]
I requested my data just for this project :D Data Structure [here](https://github.com/hatobi/bereal-gdpr-photo-toolkit/issues/6#issuecomment-1935768449)

**Comment by hatobi** [comment]
Hey @U14-dev, I just implemented the functionality to copy geo location and captions. It's in the [add-gps-data](https://github.com/hatobi/bereal-gdpr-photo-toolkit/tree/add-gps-data)-branch. If you could try running it on your files and check for any errors, I'd be really glad!

**Comment by U14-dev** [comment]
Working for me i just needed to specify the endconding on the open json to get it running so i changed _Load the JSON file_ to
 
 `with open("posts.json", encoding="utf8")`

**Comment by hatobi** [comment]
Thanks for your feedback @U14-dev. You're definitely right, it doesn't hurt to specify the encoding 😁 Just made some more changes to make the writing of metadata more robust and also tested it on a bunch more pictures with unusual characters in their captions, seemed to work just fine.
